Fixed Bug 4155: NoClassDefFoundError for com.sun.management.OperatingSystemMXBean
Catch NoClassDefFoundError so as not to blow up on JVMs where OSMXB
doesn't exist.

git-svn-id: https://vassalengine.svn.sourceforge.net/svnroot/vassalengine/VASSAL-src/trunk@8413 67b53d14-2c14-4ace-a08f-0dab2b34000c